version: "3.1"

services:
  apidb:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3312:3306"
    environment:  
      MYSQL_DATABASE: apidb
      MYSQL_ROOT_USER: anderson
      MYSQL_USER: anderson
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret